# Generated by Django 5.0 on 2024-01-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Party Cake'), (2, 'Kids Cake'), (3, 'Photo Cake'), (4, 'Regular Cake'), (5, 'Birthday Cake'), (6, 'Eggless Cake'), (7, 'Anniversary Cake')], verbose_name='Category'),
        ),
    ]
