# Generated by Django 5.0 on 2024-01-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_alter_cake_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cat',
            field=models.IntegerField(),
        ),
    ]
